### ISSUE TITLE
Laravel kanban not working

### ISSUE THREAD

**Issue by mai1237** [bhaidar/laravel-kanban#1]
I followed all the instructions but when I tried to login, the card did not appear to enter the email and password

**Comment by bhaidar** [comment]
Hello @mai1237 It's difficult to tell what's going on. Share a video of what's happening. Also, make sure you've installed the project properly, etc.

**Comment by nlvrodnie** [comment]
it works  but there is a bug when  id is missing

![image](https://user-images.githubusercontent.com/103983277/227134953-8e49eed6-bcd8-409e-b464-c79d555c9681.png)

**Comment by bhaidar** [comment]
Hello @nlvrodnie 
Thanks for bringing this up.

I've pushed a fix to make the `board` route parameter optional. It works like a charm now. Check it and let me know.

I will close the ticket for now. If you are still facing problems, you can open a new ticket.

Regards
Bill
