### ISSUE TITLE
Problem with ssl

### ISSUE THREAD

**Issue by xdendev** [bhaidar/laravel-kanban#2]
Hi
When i set APP_URL=https://mysite.com/ 
and run commands:
php artisan ziggy:generate
npm run build
app doesnot work.
Endpoint /login return just json data about routes. Component doest not load.
What i do wrong ?
Thanks

**Comment by bhaidar** [comment]
Hi @xdendev 

There shouldn't be anything special about HTTPS. I have yet to try it locally. Have you checked your asset files for .js and .css? Maybe something is not loading.

**Comment by bhaidar** [comment]
Also, try to clear the cache and config.

**Comment by bhaidar** [comment]
@xdendev I've used Laravel Sail with all default settings. Compare your docker settings to the one of Laravel Sail. Thanks
