### ISSUE TITLE
Cards reordering is not working in the below case.

### ISSUE THREAD

**Issue by Lakshan-Madushanka** [bhaidar/laravel-kanban#3]
![Video_230417113214](https://user-images.githubusercontent.com/47297673/232750750-4de4e6eb-442b-4e23-a2ce-1b1cb7b83cc8.gif)

**Comment by bhaidar** [comment]
Hello @Lakshan-Madushanka 

Please share with me the application log to see what's happening in the backend.

**Comment by Lakshan-Madushanka** [comment]
Hey @bhaidar 

I decided to spend some time to fix this and I have submitted the pull request #4 

Honestly it was a tricky one to debug, I hope you will realize what was wrong by reviewing the pull request if not tell me

**Comment by Lakshan-Madushanka** [comment]
@bhaidar could I know the status of this issue and the pull request I made (this is getting older)
